# Generated by Django 5.2.3 on 2025-06-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0002_alter_user_options_user_phone_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="custom_users",
        ),
    ]
