# Generated by Django 5.2.3 on 2025-06-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0003_alter_user_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default=891363082364,
                max_length=20,
                unique=True,
                verbose_name="Номер телефона",
            ),
            preserve_default=False,
        ),
    ]
