# Generated by Django 5.2.3 on 2025-06-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0004_remove_user_email_alter_user_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
