# Generated by Django 5.2.3 on 2025-06-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0005_alter_user_options_alter_user_phone"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
