# Generated by Django 5.2.3 on 2025-06-22 04:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0006_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "sizes",
                    models.CharField(max_length=50, verbose_name="Доступные размеры"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="Изображение товара"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("T-SHIRT", "Футболки"),
                            ("Robe", "Мантии"),
                            ("Dress", "Платья"),
                            ("ACCESSORIES", "Аксессуары"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
