# Generated by Django 5.2.3 on 2025-06-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0007_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
