# Generated by Django 5.2.3 on 2025-06-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0010_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("T-shirts", "Футболки"),
                    ("Robe", "Мантии"),
                    ("Dress", "Платья"),
                    ("Accessories", "Аксессуары"),
                ],
                max_length=20,
                verbose_name="Категория",
            ),
        ),
    ]
